Repository SSU-RETURN/emuda-front, pull requests merged in 2024-06, with the labels that each got.

#78 🔧 [Fix] 머지 후 버그 수정 ✨ [Feat] 일기, 메인화면 관련 API 연결 완료
  emuda/src/Pages/DetailDiaryView/DetailDiaryView.jsx
  emuda/src/Pages/MainView/MainView.jsx
  emuda/src/Pages/MusicCardView/MusicCardView.jsx
  emuda/src/Pages/WriteDiaryView/WriteDiaryView.jsx
Labels: :bug: bug, :sparkles: Feature, 🌷 주현아

#81 🐛 [Bug] 음악 선택 시 일기 생성 오류 해결
  emuda/src/Pages/WriteDiaryView/WriteDiaryView.jsx
Labels: :bug: bug, 🌷 주현아

#84 📬 [API] ✨ [Feat] 추천 화면 일기 미작성 API 연결, UI 수정
  emuda/src/Pages/RecommendationView/RecommendationView.jsx
  emuda/src/Pages/WriteDiaryView/WriteDiaryView.jsx
Labels: :sparkles: Feature, 📬 API, 🌷 주현아

#85 ✨ [Feat] 일기작성 UI 수정, 로딩 스피너 추가, 버튼 비활성화 기능 추가
  emuda/src/Pages/WriteDiaryView/WriteDiaryView.jsx
Labels: :sparkles: Feature, 🌷 주현아

#86 ✨ [Feat] 네트워크 오류 UI 작업
  emuda/src/Pages/NetworkErrorView/NetworkErrorView.jsx
  emuda/src/assets/ErrorIcon.svg
Labels: :sparkles: Feature, 🌷 주현아

#89 ✨ 🐛 [Feat, Bug] RecommendationView수정,
  emuda/src/Pages/DetailDiaryView/DetailDiaryView.jsx
  emuda/src/Pages/MusicCardView/MusicCardView.jsx
  emuda/src/Pages/PlayListView/PlayListView.jsx
  emuda/src/Pages/RecommendationView/MoreRecommendationView/MoreRecommendationView.jsx
  emuda/src/Pages/RecommendationView/RecommendationView.jsx
  emuda/src/Pages/WriteDiaryView/WriteDiaryView.jsx
  emuda/src/components/EmotionChart/EmotionChart.jsx
  emuda/src/components/SelectBar/SelectEmotionBar.jsx
Labels: :sparkles: Feature, 🔧 Fix, 🍀 서윤하

#88 🔧 [Fix] 취향 플리, 일기 생성 오류 해결
  emuda/src/Pages/PreferView/PreferFinView.jsx
  emuda/src/Pages/WriteDiaryView/WriteDiaryView.jsx
Labels: 📬 API, 🔧 Fix, 🌷 주현아

#92 🔧 [Fix] MainView 레이아웃 수정, 오류 해결
  emuda/src/Pages/DetailDiaryView/DetailDiaryView.jsx
  emuda/src/Pages/MainView/MainView.jsx
  emuda/src/Pages/MusicCardView/MusicCardView.jsx
  emuda/src/Pages/RecommendationView/RecommendationView.jsx
  emuda/src/Pages/WriteDiaryView/WriteDiaryView.jsx
Labels: 🔧 Fix, 🌷 주현아
