Repository SSU-RETURN/emuda-front, pull requests merged in 2024-05, with the labels that each got.

#16 ✨ [Feat] WriteDiaryView UI 작업하기
  emuda/src/Colors/Colors.js
  emuda/src/Pages/WriteDiaryView/WriteDiaryView.jsx
  emuda/src/assets/magnifyingglass.svg
  emuda/src/assets/photo_add.svg
  emuda/src/components/PlayListCell/PlayListCell.jsx
  emuda/src/main.jsx
Labels: :sparkles: Feature

#18 ✨ [Feat] PlaylistView 제작, RecommendationView 수정
  emuda/index.html
  emuda/src/App.jsx
  emuda/src/Pages/PlayListView/PlayListView.jsx
  emuda/src/Pages/RecommendationView/MoreRecommendationView/MoreRecommendationView.jsx
  emuda/src/Pages/RecommendationView/RecommendationView.jsx
  emuda/src/assets/react.svg
  emuda/src/components/AppBarInMainScreen/AppBarInMainScreen.jsx
  emuda/src/components/DailyPlaylistCell/DailyPlaylistCell.jsx
  emuda/src/components/EmotionCell/EmotionCell.jsx
  emuda/src/components/EmotionStyles/EmotionStyles.jsx
  emuda/src/components/PlayListCell/PlayListCell.jsx
  emuda/src/components/SelectBar/SelectBar.jsx
  emuda/src/components/SelectBar/SelectEmotionBar.jsx
Labels: :sparkles: Feature

#20 ✨ [Feat] SearchMusicView UI 작업완료
  emuda/src/Pages/SearchMusicView/SearchMusicView.jsx
  emuda/src/Pages/WriteDiaryView/WriteDiaryView.jsx
  emuda/src/assets/magnifyingglass.jsx
  emuda/src/assets/magnifyingglass.svg
  emuda/src/components/PlayListCell/PlayListCell.jsx
  emuda/src/main.jsx
Labels: :sparkles: Feature

#23 ✨ [Feat] EditDiaryView UI 작업완료
  emuda/src/Pages/WriteDiaryView/WriteDiaryView.jsx
  emuda/src/main.jsx
Labels: :sparkles: Feature, 🔧 Fix

#25 ✨ [Feat] DetailDiaryView UI 작업완료
  emuda/src/Pages/DetailDiaryView/DetailDiaryView.jsx
  emuda/src/main.jsx
Labels: :sparkles: Feature

#27 🐛 [Bug] 파일 경로 오류 수정, 변경된 svg파일 사용방식으로 인한 수정
  emuda/src/Pages/DetailDiaryView/DetailDiaryView.jsx
  emuda/src/Pages/PlayListView/PlayListView.jsx
Labels: :bug: bug

#29 ✨ [feat] EmotionGraph 추가
  emuda/package-lock.json
  emuda/package.json
  emuda/src/App.jsx
  emuda/src/Pages/RecommendationView/MoreRecommendationView/MoreRecommendationView.jsx
  emuda/src/Pages/RecommendationView/RecommendationView.jsx
  emuda/src/components/AppBarInEditMode/AppBarInEditMode.jsx
  emuda/src/components/EmotionChart/EmotionChart.jsx
  emuda/src/components/PlayListCell/PlayListCell.jsx
  emuda/src/main.jsx
  emuda/yarn.lock
Labels: :sparkles: Feature

#35 ✨ [feat] MainView UI 작업
  emuda/package-lock.json
  emuda/package.json
  emuda/src/App.jsx
  emuda/src/Pages/MainView/MainView.jsx
  emuda/src/components/EmotionStyles/EmotionStyles.jsx
  emuda/yarn.lock
Labels: :sparkles: Feature

#40 ✨ [Feat] 일기관련 뷰 네비게이션 연결 완료
  emuda/src/Pages/DetailDiaryView/DetailDiaryView.jsx
  emuda/src/Pages/MusicCardView/MusicCardView.jsx
  emuda/src/Pages/SearchMusicView/SearchMusicView.jsx
  emuda/src/Pages/WriteDiaryView/WriteDiaryView.jsx
  emuda/src/components/AppBarInViewMode/AppBarInViewMode.jsx
Labels: :sparkles: Feature

#43 ✨ [Feat] EmotionChat 컴포넌트 반영
  emuda/src/Pages/DetailDiaryView/DetailDiaryView.jsx
  emuda/src/Pages/DiaryEmotionGraphView/DiaryEmotionGraphView.jsx
  emuda/src/Pages/WriteDiaryView/WriteDiaryView.jsx
  emuda/src/components/EmotionChart/EmotionChart.jsx
  emuda/src/main.jsx
Labels: :sparkles: Feature

#50 ✨ [Feat] 로그인 API 연결 완료
  emuda/.gitignore
  emuda/package-lock.json
  emuda/package.json
  emuda/src/Pages/LoginView/LoginView.jsx
  emuda/src/Pages/PreferView/PreferStartView.jsx
  emuda/src/apis/user.js
  emuda/src/config/config.js
  emuda/yarn.lock
Labels: :sparkles: Feature

#58 ✨ [Feat] 로그아웃 구현
  emuda/src/Pages/SettingVIew/SettingView.jsx
Labels: :sparkles: Feature

#60 ✨ [Feat] 탈퇴 API 구현
  emuda/src/Pages/SettingVIew/SettingView.jsx
Labels: :sparkles: Feature

#63 ✨ [Feat] 취향 조회 API, 취향 업데이트 API 연결
  emuda/src/Pages/PreferView/PreferFinView.jsx
  emuda/src/Pages/PreferView/PreferFirstView.jsx
  emuda/src/Pages/PreferView/PreferSecondView.jsx
  emuda/src/Pages/SettingVIew/SettingView.jsx
Labels: :sparkles: Feature, 🌻 정민지

#68 ✨ [Feat] 회원정보 수정 API 연결
  emuda/src/Pages/EditMemberInfoView/EditMemberInfoView.jsx
  emuda/src/Pages/LoginView/LoginView.jsx
  emuda/src/components/AppBarInMainScreen/AppBarInMainScreen.jsx
Labels: :sparkles: Feature, 🌻 정민지

#73 ✨ [Feat] 일기 생성 API , 메인화면, 일기 조회 작업
  emuda/src/Pages/DetailDiaryView/DetailDiaryView.jsx
  emuda/src/Pages/MainView/MainView.jsx
  emuda/src/Pages/WriteDiaryView/WriteDiaryView.jsx
Labels: :sparkles: Feature, 🌷 주현아

#74 🔧 [Fix] 상단바, 하단바 고정되게 수정
  emuda/src/Pages/DetailDiaryView/DetailDiaryView.jsx
  emuda/src/Pages/MainView/MainView.jsx
  emuda/src/Pages/PlayListView/PlayListView.jsx
  emuda/src/Pages/PreferView/PreferFinView.jsx
  emuda/src/Pages/PreferView/PreferFirstView.jsx
  emuda/src/Pages/PreferView/PreferSecondView.jsx
  emuda/src/Pages/RecommendationView/MoreRecommendationView/MoreRecommendationView.jsx
  emuda/src/Pages/RecommendationView/RecommendationView.jsx
  emuda/src/Pages/SearchMusicView/SearchMusicView.jsx
  emuda/src/Pages/SettingVIew/SettingView.jsx
  emuda/src/Pages/SignUpView/SignUpView.jsx
  emuda/src/Pages/WriteDiaryView/WriteDiaryView.jsx
  emuda/src/components/AppBarInEditMode/AppBarInEditMode.jsx
  emuda/src/components/AppBarInMainScreen/AppBarInMainScreen.jsx
  emuda/src/components/AppBarInViewMode/AppBarInViewMode.jsx
  emuda/src/components/BottomNavigationBar/BottomNavigationBar.jsx
Labels: 🔧 Fix, 🌻 정민지

#75 🔧 [Fix] 회원가입 화면 UI 수정
  emuda/src/Pages/PreferView/PreferFirstView.jsx
  emuda/src/Pages/PreferView/PreferSecondView.jsx
  emuda/src/Pages/SignUpView/SignUpComView.jsx
  emuda/src/Pages/SignUpView/SignUpView.jsx
Labels: 🔧 Fix, 🌻 정민지

#77 ✨ [Feat] 일기 월별 조회, 삭제, 수정 API 작업
  emuda/src/Pages/DetailDiaryView/DetailDiaryView.jsx
  emuda/src/Pages/MainView/MainView.jsx
  emuda/src/Pages/WriteDiaryView/WriteDiaryView.jsx
  emuda/src/components/AppBarInViewMode/AppBarInViewMode.jsx
  emuda/src/components/EmotionStyles/EmotionStyles.jsx
  emuda/src/components/EmotionStyles/EmotionStyles2.jsx
Labels: :sparkles: Feature, 🌷 주현아
